// <auto-generated />
using GamersInfoApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GamersInfoApp.Migrations
{
    [DbContext(typeof(GamersInfoAppContext))]
    partial class GamersInfoAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GamersInfoApp.Models.Game", b =>
                {
                    b.Property<int>("GameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GameID"));

                    b.Property<string>("GameGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameID");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("GamersInfoApp.Models.Gamer", b =>
                {
                    b.Property<int>("GamerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GamerID"));

                    b.Property<int?>("GamerAge")
                        .HasColumnType("int");

                    b.Property<string>("GamerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GamerID");

                    b.ToTable("Gamer");
                });

            modelBuilder.Entity("GamersInfoApp.Models.Gamer_Game", b =>
                {
                    b.Property<int>("GamerGameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GamerGameID"));

                    b.Property<int>("GameID")
                        .HasColumnType("int");

                    b.Property<int>("GamerID")
                        .HasColumnType("int");

                    b.Property<int>("HoursPlayed")
                        .HasColumnType("int");

                    b.HasKey("GamerGameID");

                    b.HasIndex("GameID");

                    b.HasIndex("GamerID");

                    b.ToTable("Gamer_Game");
                });

            modelBuilder.Entity("GamersInfoApp.Models.Gamer_Game", b =>
                {
                    b.HasOne("GamersInfoApp.Models.Game", "Game")
                        .WithMany("Gamer_Games")
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GamersInfoApp.Models.Gamer", "Gamer")
                        .WithMany("Gamer_Games")
                        .HasForeignKey("GamerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Gamer");
                });

            modelBuilder.Entity("GamersInfoApp.Models.Game", b =>
                {
                    b.Navigation("Gamer_Games");
                });

            modelBuilder.Entity("GamersInfoApp.Models.Gamer", b =>
                {
                    b.Navigation("Gamer_Games");
                });
#pragma warning restore 612, 618
        }
    }
}
